language: java

java:
  - "9"

install:
  - ./gradlew assemble

script:
  - ./gradlew installDist
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t cjblink1/srtsignin-role-service:$TRAVIS_COMMIT .
  - docker push cjblink1/srtsignin-role-service:$TRAVIS_COMMIT
  - git clone --depth=1 https://github.com/srtsignin/config.git
